---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
- type: heading
  label: Data Files
- type: directory
  path: _data/en
  label: en
  create: all
  match: "**/*"
  new_doc_ext: yml
- type: directory
  path: _data/ja
  label: ja
  create: all
  match: "**/*"
  new_doc_ext: ".yml"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
